### ISSUE TITLE
User Story BE #1: User registration

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#1]
EPIC: **User Authentication**

As a **developer**, I want to **access an API endpoint for registration**, so that I can **create users and profiles**.  

**Acceptance Criteria:**
- The API endpoint for user registration is finsished.
- Users can provide necessary information for registration.
- After successful registration, a new user and profile are created.

**Tasks:**
- [x] Create API endpoint for user registration.
- [x] Validate user input data.
- [x] Create user account and profile.
