### ISSUE TITLE
User Story BE #10: Posts CRUD

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#10]
EPIC: **Posts**

As a **developer**, I want to **perform CRUD operations for posts**, so that I can **allow users to post content**.

**Acceptance Criteria:**
- Users can create, read, update, and delete posts.
- Users can upload and retrieve images and videos for their posts.
-Posts can be retrieved from the API based on specified criteria.

**Tasks:**
- [x] Define the structure of posts.
- [x] Implement API endpoints for creating, updating, deleting, and retrieving posts.
- [x] Create API endpoints for uploading and retrieving images and videos.
- [x] Validate data and authorization.
