### ISSUE TITLE
User Story FE #5: Navigation

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#22]
EPIC: **General UX**

As a **site user**, I expect **clear and intuitive site navigation**, so that I can **easily navigate the application**.

**Acceptance Criteria:**
- The navigation menu should be clearly visible and easily accessible on all pages of the application.
- Navigation content depends on the users authentication status.

**Tasks:**
- [x] Design site navigation.
- [x] Ensure that navigation elements are responsive and accessible on various screen sizes.
- [x] Show navigation links based on users authentication status.
