### ISSUE TITLE
User Story FE #10: Deactivate profile

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#27]
EPIC: **Profile**

As a **site user**, I want to **deactivate my profile**, so that I can **show that I am unavailable at the moment**.

**Acceptance Criteria:**
- Users have the option to deactivate their profiles temporarily.
- Deactivated profiles are hidden from public view.
- Deactivated profiles can be reactivated.

**Tasks:**
- [ ] Add a deactivation toggle to the user profile.
- [ ] Hide deactivated profiles from feeds.
- [ ] Indicate that profile was deactivated in comment.
- [ ] Ensure everything is visible again on reactivation.
