### ISSUE TITLE
User Story FE #15: Save posts

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#32]
EPIC: **Posts**

As a **site user**, I want to **save posts**, so that I can **find them again easily**.

**Acceptance Criteria:**
- Posts can be saved.
- Saved posts are shown in the sidebar on bigger screens.
- Saved posts are shown in a separate page on smaller screens.

**Tasks:**
- [x] Add button to save a post.
- [x] Show saved posts in sidebar.
- [x] Show saved posts in separate page.
