### ISSUE TITLE
User Story FE #19: Dog adopted

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#36]
EPIC: **Dog Posts**

As a **shelter**, I want to **mark a dog as adopted**, so that I can **show successful adoptions**. 

**Acceptance Criteria:**
- Dogs can be marked as adopted by shelters.
- Posts can be filtered for adopted dogs.
- Adopted dogs don´t show up in matching/searching for adopters.

**Tasks:**
- [x] Add adopted button to dog post.
- [x] Add filter for adopted dogs.
- [x] Ensure adopted dogs can´t be matched with adopters.
