### ISSUE TITLE
User Story FE #22: Notifications

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#39]
EPIC: **Notifications and Communication**

As a **site user**, I want to **receive notifications**, so that I can **stay up-to-date**.

**Acceptance Criteria:**
- Notifications are shown for relevant events.
- Notifications can be marked as read.
- Notifications are shown in the sidebar for bigger screens and on separate page for smaller screens.

**Tasks:**
- [ ] Display notifications.
- [ ] Add mark as read button.
- [ ] Add mark all as read button.
- [ ] Show notifications in sidebar.
- [ ] Show notifications in separate page.
