### ISSUE TITLE
Dev Task #1: Set up project

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/pawfect-match#41]
**Description:**
Set the project up and install the necessary libraries.

**Tasks:**
- [x]  Set up virtual environment in local IDE
- [x] Install Django
- [x] Link to Cloudinary
- [x] Link to Database
